services:
  nginx:
    image: vanyauhalin/nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./etc/acme:/etc/acme
    - ./etc/nginx/ssl:/etc/nginx/ssl
    - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
    - AE_EMAIL=hi@example.com
    - AE_DOMAINS=example.com
