services:
  nginx:
    image: vanyauhalin/nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./etc/acme:/etc/acme
    - ./etc/nginx/ssl:/etc/nginx/ssl
    - ./nginx.conf.template:/etc/nginx/nginx.conf.template
    environment:
    - NGINX_SERVER_ALIAS=www.example.com
    - NGINX_SERVER_NAME=example.com
    - AE_EMAIL=hi@example.com
    - AE_DOMAINS=www.example.com,example.com
