[tools]
hadolint   = "2.12.0" # https://github.com/hadolint/hadolint/
shellcheck = "0.10.0" # https://github.com/koalaman/shellcheck/
shfmt      = "3.10.0" # https://github.com/mvdan/sh/

# The tools listed below are used in the project.
# However, you probably installed them globally.
# awk    = "5.3.1"  # https://gnu.org/software/gawk/
# docker = "27.3.1" # https://docker.com/
# grep   = "3.11"   # https://gnu.org/software/grep/
# make   = "4.4.1"  # https://gnu.org/software/make/
