name: Audit a Docker image

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Lint the Dockerfile and shell scripts
      run: make lint
