name: Release a Docker image

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

on:
  push:
    tags:
    - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vanyauhalin/nginx

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Extract metadata from Dockerfile
      id: dockerfile
      run: |
        echo "labels<<EOF" >> "$GITHUB_ENV"
        while IFS= read -r c; do
          case "$c" in
          LABEL*)
            c=$(echo "$c" | sed 's/^LABEL[[:space:]]*//')
            n=$(echo "$c" | cut -d= -f1 | xargs)
            v=$(echo "$c" | cut -d= -f2- | sed 's/"//g')
            echo "$n=$v" >> "$GITHUB_ENV"
            ;;
          esac
        done < Dockerfile
        echo "EOF" >> "$GITHUB_ENV"

    - name: Extract metadata for Docker
      id: docker
      uses: docker/metadata-action@v5
      with:
        images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
        labels: ${{steps.dockerfile.outputs.labels}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{steps.docker.outputs.tags}}
        labels: ${{steps.docker.outputs.labels}}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
        subject-digest: ${{steps.push.outputs.digest}}
        push-to-registry: true
