name: Release a Docker image

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

on:
  push:
    tags:
    - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ""
  DOCKERFILE_LABELS: ""

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Extract image name from Dockerfile
      run: |
        t=$(< Dockerfile grep "LABEL org.opencontainers.image.title=")
        v=$(echo "$t" | cut --delimiter="=" --fields=2- | sed "s/\"//g")
        echo "IMAGE_NAME=${{github.actor}}/$v" >> "$GITHUB_ENV"

    - name: Extract labels from Dockerfile
      run: |
        echo "DOCKERFILE_LABELS<<EOF" >> "$GITHUB_ENV"
        while IFS= read -r c; do
          case "$c" in
          LABEL*)
            c=$(echo "$c" | sed "s/^LABEL[[:space:]]*//")
            n=$(echo "$c" | cut --delimiter="=" --fields=1)
            v=$(echo "$c" | cut --delimiter="=" --fields=2- | sed "s/\"//g")
            echo "$n=$v" >> "$GITHUB_ENV"
            ;;
          esac
        done < Dockerfile
        echo "EOF" >> "$GITHUB_ENV"

    - name: Extract metadata for Docker
      id: docker
      uses: docker/metadata-action@v5
      with:
        images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
        labels: ${{env.DOCKERFILE_LABELS}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{steps.docker.outputs.tags}}
        labels: ${{steps.docker.outputs.labels}}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
        subject-digest: ${{steps.push.outputs.digest}}
        push-to-registry: true
